name: Nix
'on':
  push:
    paths:
    - docs/**
    - '**/*.md'
    - '**/*.qmd'
    - .envrc
    branches:
    - main
    - '*.x.x'
  pull_request:
    paths:
    - docs/**
    - '**/*.md'
    - '**/*.qmd'
    - .envrc
    branches:
    - main
    - '*.x.x'
  merge_group: null
permissions:
  contents: none
jobs:
  nix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-latest
        - macos-15
        python-version:
        - '3.10'
        - '3.14'
    steps:
    - run: echo "No build required"
