name: PyPI Pre-Release
'on':
  schedule:
  - cron: 0 0 * * 0
  workflow_dispatch: null
concurrency:
  group: pre-release
  cancel-in-progress: false
jobs:
  pre-release:
    if: github.repository_owner == 'playground-nils'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: install python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: install uv
      uses: astral-sh/setup-uv@v7.3.0
    - uses: extractions/setup-just@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: compute ibis version
      id: get-version
      run: echo "value=$(just bump-version)" | tee -a "$GITHUB_OUTPUT"
    - name: build wheel and source dist
      run: uv build
      if: contains(steps.get-version.outputs.value, '.dev')
    - name: publish pre-release wheel to test pypi index
      if: contains(steps.get-version.outputs.value, '.dev')
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
      with:
        repository-url: https://test.pypi.org/legacy/
        attestations: false
    - name: publish pre-release wheel to pypi
      if: contains(steps.get-version.outputs.value, '.dev')
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
